version: '3'
services:
  fpm_mmp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpm_mmp

    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Add helper script
      - ../../bin/magento:/bin/magento
      - ../../magento/backup:/var/www/backup

      # Xdebug config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      PHP_EXTENSION_XDEBUG: 1

    networks:
      - webnet_mmp

  nginx_mmp:
    image: nginx

    container_name: nginx_mmp

    ports:
      - 3080:80
      - 3443:443
    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Mounting the SSL certs
      - ../../etc/ssl:/var/www/certs

      - ./docker.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fpm_mmp
    networks:
      - webnet_mmp

  mailhog_mmp:
    image: mailhog/mailhog
    container_name: mailhog_mmp
    ports:
      - 8888:8025
    networks:
      - webnet_mmp

  db_mmp:
    image: percona:8
    container_name: db_mmp
    volumes:
      - ../../services/db-data/mmp:/var/lib/mysql
      - ../../source/db:/backup
      - ../../bin/db:/bin/db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_mmp

  #ALTER USER root IDENTIFIED WITH mysql_native_password BY 'admin123';

  phpmyadmin_mmp:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mmp
    ports:
      - 9999:80
    environment:
      PMA_HOST: db_mmp
      PMA_USER: root
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_mmp

  redis_mmp:
    image: redis:5.0
    container_name: redis_mmp
    networks:
      - webnet_mmp

  es_mmp:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es_mmp
    environment:
      - discovery.type=single-node
      - node.name=es_mmp
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../services/es-data/mmp:/usr/share/elasticsearch/data
    ports:
      - 7777:9200
    networks:
      - webnet_mmp

networks:
  webnet_mmp: