version: '3'
services:
  fpm_ubt:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpm_ubt

    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Add helper script
      - ../../bin/magento:/bin/magento
      - ../../magento/backup:/var/www/backup

      # Xdebug config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      PHP_EXTENSION_XDEBUG: 1

    networks:
      - webnet_ubt

  nginx_ubt:
    image: nginx

    container_name: nginx_ubt

    ports:
      - 4080:80
      - 4443:443
    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Mounting the SSL certs
      - ../../etc/ssl:/var/www/certs

      - ./docker.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fpm_ubt
    networks:
      - webnet_ubt

  mailhog_ubt:
    image: mailhog/mailhog
    container_name: mailhog_ubt
    ports:
      - 2222:8025
    networks:
      - webnet_ubt

  db_ubt:
    image: mariadb:10.4
    container_name: db_ubt
    volumes:
      - ../../services/db-data/ubt:/var/lib/mysql
      - ../../source/db:/backup
      - ../../bin/db:/bin/db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_ubt

  #ALTER USER root IDENTIFIED WITH mysql_native_password BY 'admin123';

  phpmyadmin_ubt:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ubt
    ports:
      - 1111:80
    environment:
      PMA_HOST: db_ubt
      PMA_USER: root
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_ubt

  redis_ubt:
    image: redis:5.0
    container_name: redis_ubt
    networks:
      - webnet_ubt

  es_ubt:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es_ubt
    environment:
      - discovery.type=single-node
      - node.name=es_ubt
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../services/es-data/ubt:/usr/share/elasticsearch/data
    ports:
      - 3333:9200
    networks:
      - webnet_ubt

networks:
  webnet_ubt: