version: '3'
services:
  fpm_sample:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpm_sample

    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Add helper script
      - ../../bin/magento:/bin/magento
      - ../../magento/backup:/var/www/backup

      # Xdebug config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      PHP_EXTENSION_XDEBUG: 1

    networks:
      - webnet_sample

  nginx_sample:
    image: nginx

    container_name: nginx_sample

    ports:
      - 3080:80
      - 3443:443
    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Mounting the SSL certs
      - ../../etc/ssl:/var/www/certs

      - ./docker.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fpm_sample
    networks:
      - webnet_sample

  mailhog_sample:
    image: mailhog/mailhog
    container_name: mailhog_sample
    ports:
      - 8888:8025
    networks:
      - webnet_sample

  db_sample:
    image: percona:8
    container_name: db_sample
    volumes:
      - ../../services/db-data/sample:/var/lib/mysql
      - ../../source/db:/backup
      - ../../bin/db:/bin/db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_sample

  #ALTER USER root IDENTIFIED WITH mysql_native_password BY 'admin123';

  phpmyadmin_sample:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_sample
    ports:
      - 9999:80
    environment:
      PMA_HOST: db_sample
      PMA_USER: root
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_sample

  redis_sample:
    image: redis:5.0
    container_name: redis_sample
    networks:
      - webnet_sample

  es_sample:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es_sample
    environment:
      - discovery.type=single-node
      - node.name=es_sample
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../services/es-data/sample:/usr/share/elasticsearch/data
    ports:
      - 7777:9200
    networks:
      - webnet_sample

networks:
  webnet_sample: