version: '3'
services:
  fpm_uc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpm_uc

    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Add helper script
      - ../../bin/magento:/bin/magento
      - ../../magento/backup:/var/www/backup

      # Xdebug config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      PHP_EXTENSION_XDEBUG: 1

    networks:
      - webnet_uc

  nginx_uc:
    image: nginx

    container_name: nginx_uc

    ports:
      - 4080:80
      - 4443:443
    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Mounting the SSL certs
      - ../../etc/ssl:/var/www/certs

      - ./docker.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fpm_uc
    networks:
      - webnet_uc

  mailhog_uc:
    image: mailhog/mailhog
    container_name: mailhog_uc
    ports:
      - 2222:8025
    networks:
      - webnet_uc

  db_uc:
    image: percona:8
    container_name: db_uc
    volumes:
      - ../../services/db-data/uc:/var/lib/mysql
      - ../../source/db:/backup
      - ../../bin/db:/bin/db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_uc

  #ALTER USER root IDENTIFIED WITH mysql_native_password BY 'admin123';

  phpmyadmin_uc:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_uc
    ports:
      - 1111:80
    environment:
      PMA_HOST: db_uc
      PMA_USER: root
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_uc

  redis_uc:
    image: redis:5.0
    container_name: redis_uc
    networks:
      - webnet_uc

  es_uc:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es_uc
    environment:
      - discovery.type=single-node
      - node.name=es_uc
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../services/es-data/uc:/usr/share/elasticsearch/data
    ports:
      - 3333:9200
    networks:
      - webnet_uc

networks:
  webnet_uc: