version: '3'
services:
  fpm_magento:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpm_magento

    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Add helper script
      - ../../bin/magento:/bin/magento
      - ../../magento/backup:/var/www/backup

      # Xdebug config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      PHP_EXTENSION_XDEBUG: 1

    networks:
      - webnet_magento

  nginx_magento:
    image: nginx

    container_name: nginx_magento

    ports:
      - 3080:80
      - 3444:443
    volumes:
      # Mounting the project folder
      - ./html:/var/www/html/

      # Mounting the SSL certs
      - ../../etc/ssl:/var/www/certs

      - ./docker.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fpm_magento
    networks:
      - webnet_magento

  mailhog_magento:
    image: mailhog/mailhog
    container_name: mailhog_magento
    ports:
      - 8888:8025
    networks:
      - webnet_magento

  db_magento:
    image: percona:8
    container_name: db_magento
    volumes:
      - ../../services/db-data/magento:/var/lib/mysql
      - ../../source/db:/backup
      - ../../bin/db:/bin/db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_magento

  #ALTER USER root IDENTIFIED WITH mysql_native_password BY 'admin123';

  phpmyadmin_magento:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_magento
    ports:
      - 9999:80
    environment:
      PMA_HOST: db_magento
      PMA_USER: root
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - webnet_magento

  redis_magento:
    image: redis:5.0
    container_name: redis_magento
    networks:
      - webnet_magento

  es_magento:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es_magento
    environment:
      - discovery.type=single-node
      - node.name=es_magento
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../services/es-data/magento:/usr/share/elasticsearch/data
    ports:
      - 7777:9200
    networks:
      - webnet_magento

networks:
  webnet_magento:
